// Sample data for in-memory storage
const getSampleProducts = () => {

    const sampleProducts = [
      {
        name: "Digital Blood Pressure Monitor",
        description: "Accurate and easy-to-use blood pressure monitor for home use.",
        price: 1500,
        image: "https://via.placeholder.com/300x300/e3f2fd/1976d2?text=BP+Monitor",
        category: "Medical Devices",
        stock: 50,
        isFeatured: true,
        isNewArrival: false,
      },
      {
        name: "Vitamin D3 Supplements (60 caps)",
        description: "High-potency Vitamin D3 for bone health and immunity.",
        price: 450,
        image: "https://via.placeholder.com/300x300/fff3e0/f57c00?text=Vitamin+D3",
        category: "Supplements",
        stock: 100,
        isFeatured: true,
        isNewArrival: false,
      },
      {
        name: "Infrared Thermometer",
        description: "Non-contact thermometer for quick and hygienic temperature checks.",
        price: 999,
        image: "https://via.placeholder.com/300x300/f3e5f5/8e24aa?text=Thermometer",
        category: "Medical Devices",
        stock: 75,
        isFeatured: true,
        isNewArrival: false,
      },
      {
        name: "N95 Face Masks (Pack of 10)",
        description: "Certified N95 masks for superior protection against airborne particles.",
        price: 299,
        image: "https://via.placeholder.com/300x300/e8f5e8/43a047?text=N95+Masks",
        category: "Personal Care",
        stock: 200,
        isFeatured: true,
        isNewArrival: false,
      },
      {
        name: "Smart Glucose Meter",
        description: "Connects to your smartphone for easy tracking of blood glucose levels.",
        price: 2200,
        image: "https://via.placeholder.com/300x300/e1f5fe/0277bd?text=Glucose+Meter",
        category: "Medical Devices",
        stock: 30,
        isFeatured: false,
        isNewArrival: true,
      },
      {
        name: "Organic Protein Powder (Vanilla)",
        description: "Plant-based protein for muscle recovery and daily nutrition.",
        price: 1200,
        image: "https://via.placeholder.com/300x300/fff8e1/ff8f00?text=Protein+Powder",
        category: "Supplements",
        stock: 80,
        isFeatured: false,
        isNewArrival: true,
      },
      {
        name: "Portable Oxygen Concentrator",
        description: "Lightweight and efficient oxygen therapy on the go.",
        price: 25000,
        image: "https://via.placeholder.com/300x300/f1f8e9/558b2f?text=Oxygen+Concentrator",
        category: "Medical Devices",
        stock: 10,
        isFeatured: false,
        isNewArrival: true,
      },
      {
        name: "First Aid Kit (Travel Size)",
        description: "Compact kit with essential supplies for minor injuries.",
        price: 550,
        image: "https://via.placeholder.com/300x300/ffebee/d32f2f?text=First+Aid+Kit",
        category: "Emergency Supplies",
        stock: 60,
        isFeatured: false,
        isNewArrival: true,
      },
      {
        name: "Digital Stethoscope",
        description: "Advanced digital stethoscope with noise reduction and recording capabilities.",
        price: 3500,
        image: "https://via.placeholder.com/300x300/e3f2fd/1565c0?text=Digital+Stethoscope",
        category: "Medical Devices",
        stock: 25,
        isFeatured: true,
        isNewArrival: false,
      },
      {
        name: "Surgical Gloves (Box of 100)",
        description: "Latex-free surgical gloves for medical professionals.",
        price: 899,
        image: "https://via.placeholder.com/300x300/f3e5f5/7b1fa2?text=Surgical+Gloves",
        category: "Medical Supplies",
        stock: 150,
        isFeatured: false,
        isNewArrival: false,
      },
      {
        name: "Omega-3 Fish Oil Capsules",
        description: "High-quality omega-3 supplements for heart and brain health.",
        price: 750,
        image: "https://via.placeholder.com/300x300/fff3e0/ef6c00?text=Omega-3+Fish+Oil",
        category: "Supplements",
        stock: 120,
        isFeatured: true,
        isNewArrival: false,
      },
      {
        name: "Pulse Oximeter",
        description: "Fingertip pulse oximeter for measuring blood oxygen saturation.",
        price: 1200,
        image: "https://via.placeholder.com/300x300/e0f2f1/00695c?text=Pulse+Oximeter",
        category: "Medical Devices",
        stock: 80,
        isFeatured: false,
        isNewArrival: true,
      },
      {
        name: "Wheelchair (Lightweight)",
        description: "Lightweight aluminum wheelchair for mobility assistance.",
        price: 15000,
        image: "https://via.placeholder.com/300x300/e8eaf6/3f51b5?text=Wheelchair",
        category: "Mobility Aids",
        stock: 20,
        isFeatured: false,
        isNewArrival: true,
      },
    ];

  
  // Add IDs to products
  return sampleProducts.map((product, index) => ({
    ...product,
    _id: `prod${index + 1}`,
    id: `prod${index + 1}`,
  }));
};

module.exports = { getSampleProducts };
